export const ACCOUNTS_LOADED = "ACCOUNTS_LOADED";

export const DATA_POSTED = "DATA_POSTED";

export const ORDERS_HISTORY_LOADED = "ORDERS_HISTORY_LOADED";

export const ORDERS_LOADED = "ORDERS_LOADED";

export const PRIVATE_ORDER_HISTORY_LOADED = "PRIVATE_ORDER_HISTORY_LOADED";

export const UPDATE_ACCOUNT_ID = "UPDATE_ACCOUNT_ID";

export const UPDATED_STATE = "UPDATED_STATE";
